export const VARIABLE_BANKS: Record<string, readonly string[]> = {
  descriptors: [
    "ethereal",
    "weathered",
    "luminous",
    "tiny",
    "colossal",
    "melancholic",
    "chaotic",
    "serene",
    "ancient",
    "futuristic",
    "crystalline",
    "mossy",
    "gleaming",
    "shadowy",
    "whimsical",
    "ominous",
    "delicate",
    "rugged",
    "ornate",
    "minimalist",
    "surreal",
    "nostalgic",
    "radiant",
    "crumbling",
    "velvety",
    "sharp",
    "hollow",
    "dense",
    "translucent",
    "forgotten",
  ],
  subjects: [
    "astronaut",
    "dragon",
    "lighthouse",
    "violinist",
    "robot",
    "fox",
    "cathedral",
    "submarine",
    "samurai",
    "garden",
    "owl",
    "clocktower",
    "ballerina",
    "pirate ship",
    "mechanic",
    "witch",
    "baker",
    "mountain",
    "telescope",
    "koi pond",
    "motorcycle",
    "library",
    "phoenix",
    "street musician",
    "hot air balloon",
    "blacksmith",
    "observatory",
    "carousel",
    "wolf",
    "greenhouse",
  ],
  actions: [
    "dancing",
    "floating",
    "reading",
    "painting",
    "running",
    "meditating",
    "exploding",
    "whispering",
    "building",
    "dreaming",
    "gardening",
    "sailing",
    "sketching",
    "climbing",
    "laughing",
    "sleeping",
    "cooking",
    "photographing",
    "wandering",
    "repairing",
    "stargazing",
    "weaving",
    "diving",
    "writing",
    "celebrating",
    "hiding",
    "glowing",
    "melting",
    "blooming",
    "vanishing",
  ],
  styles: [
    "oil painting",
    "pixel art",
    "watercolor",
    "comic book",
    "ukiyo-e",
    "surrealism",
    "art deco",
    "low poly",
    "noir",
    "impressionist",
    "charcoal sketch",
    "stained glass",
    "claymation",
    "vaporwave",
    "woodcut print",
    "pop art",
    "cinematic",
    "isometric",
    "storybook",
    "blueprint",
    "mosaic",
    "ink wash",
    "retro poster",
    "paper collage",
    "neon line art",
    "baroque",
    "cubist",
    "anime",
    "folk art",
    "matte painting",
  ],
  backgrounds: [
    "stormy ocean",
    "neon city",
    "misty forest",
    "desert dusk",
    "space station",
    "candlelit library",
    "rainy alley",
    "sunflower field",
    "arctic tundra",
    "floating islands",
    "volcanic crater",
    "bamboo grove",
    "subway tunnel",
    "rooftop at midnight",
    "coral reef",
    "snowy village",
    "abandoned factory",
    "cherry blossom park",
    "crystal cave",
    "harbor at dawn",
    "thundercloud skyline",
    "meadow in spring",
    "ancient ruins",
    "aurora sky",
    "busy marketplace",
    "underwater kelp forest",
    "foggy moor",
    "palm beach",
    "clockwork city",
    "autumn hillside",
  ],
  colors: [
    "teal and gold",
    "crimson and black",
    "pastel pink",
    "monochrome",
    "electric blue",
    "earth tones",
    "violet haze",
    "sunset orange",
    "silver and emerald",
    "sepia",
    "cobalt and cream",
    "magenta and cyan",
    "rust and sage",
    "midnight blue",
    "coral and ivory",
    "lime and charcoal",
    "peach and lavender",
    "bronze and navy",
    "mint and rose",
    "amber and indigo",
    "slate and copper",
    "cherry red",
    "frost white",
    "jade and onyx",
    "honey gold",
    "plum and silver",
    "turquoise mist",
    "sand and terracotta",
    "ink black",
    "rainbow gradient",
  ],
};

export function getWordsForCategory(category: string): readonly string[] {
  return VARIABLE_BANKS[category] ?? [];
}

export function pickRandomWords(category: string, count: number, random: () => number): string[] {
  const pool = [...getWordsForCategory(category)];
  if (pool.length === 0) {
    return [];
  }

  const picked: string[] = [];
  while (picked.length < count && pool.length > 0) {
    const index = Math.floor(random() * pool.length);
    picked.push(pool.splice(index, 1)[0]);
  }
  return picked;
}
